#!/bin/bash
# =============================================================================
# ngrok Webhook Tunnel Setup Script
# =============================================================================
# Purpose : Establish a publicly accessible HTTPS URL for the BFF webhook endpoint
#           so Composio OUTLOOK_NEW_MESSAGE_TRIGGER can deliver events in real-time.
#
# Usage   : bash scripts/setup-ngrok-tunnel.sh
#           bash scripts/setup-ngrok-tunnel.sh --install   # Install ngrok first
#           bash scripts/setup-ngrok-tunnel.sh --status    # Check tunnel status
#           bash scripts/setup-ngrok-tunnel.sh --stop      # Stop tunnel
#
# Prerequisites:
#   1. Create a free account at https://dashboard.ngrok.com
#   2. Get your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken
#   3. Set env: export NGROK_AUTHTOKEN="your-authtoken-here"
#      Or edit NGROK_AUTHTOKEN below
#
# Output:
#   - Public HTTPS URL written to /root/.openclaw/workspace/.webhook-url
#   - ngrok logs at /root/.openclaw/logs/ngrok.log
#   - systemd service at ~/.config/systemd/user/ngrok-webhook.service
# =============================================================================

set -euo pipefail

# ─── Configuration ───────────────────────────────────────────────────────────
NGROK_AUTHTOKEN="${NGROK_AUTHTOKEN:-}"   # Fill in your authtoken here
NGROK_CONFIG_DIR="${HOME}/.config/ngrok"
NGROK_CONFIG_FILE="${NGROK_CONFIG_DIR}/ngrok.yml"
NGROK_LOG_FILE="/root/.openclaw/logs/ngrok.log"
WEBHOOK_URL_FILE="/root/.openclaw/workspace/.webhook-url"
LOCAL_TARGET="${LOCAL_TARGET:-http://127.0.0.1:8787}"
TUNNEL_NAME="mail-webhook"
TUNNEL_REGION="${NGROK_REGION:-ap}"
BFF_WEBHOOK_PORT=8787

# ─── ANSI Colors ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; }

# ─── Helper Functions ────────────────────────────────────────────────────────

check_ngrok_installed() {
    if command -v ngrok &>/dev/null; then
        return 0
    fi
    return 1
}

install_ngrok() {
    info "Installing ngrok..."

    # Detect architecture
    ARCH="$(uname -m)"
    case "${ARCH}" in
        x86_64)  ARCH_STR="amd64" ;;
        aarch64|arm64) ARCH_STR="arm64" ;;
        *)
            error "Unsupported architecture: ${ARCH}"
            error "Please install ngrok manually: https://ngrok.com/download"
            exit 1
            ;;
    esac

    # Download
    TMPDIR=$(mktemp -d)
    wget -q -O "${TMPDIR}/ngrok.zip" \
        "https://bin.equinox.io/c/bNyjBCzDGIu/ngrok-stable-linux-${ARCH_STR}.zip" \
        || curl -sL -o "${TMPDIR}/ngrok.zip" \
        "https://bin.equinox.io/c/bNyjBCzDGIu/ngrok-stable-linux-${ARCH_STR}.zip"

    # Install
    sudo unzip -q -o "${TMPDIR}/ngrok.zip" -d /usr/local/bin/
    sudo chmod +x /usr/local/bin/ngrok
    rm -rf "${TMPDIR}"

    if check_ngrok_installed; then
        success "ngrok installed: $(ngrok version --width 60 | head -1)"
    else
        error "ngrok installation failed"
        exit 1
    fi
}

configure_ngrok() {
    info "Configuring ngrok..."

    # Ensure config directory exists
    mkdir -p "${NGROK_CONFIG_DIR}"
    mkdir -p "$(dirname "${NGROK_LOG_FILE}")"

    # If authtoken provided via environment, save it
    if [[ -n "${NGROK_AUTHTOKEN}" ]]; then
        ngrok config add-authtoken "${NGROK_AUTHTOKEN}" 2>/dev/null || true
    fi

    # Write ngrok config file
    cat > "${NGROK_CONFIG_FILE}" <<EOF
# ngrok configuration
# Auto-generated by setup-ngrok-tunnel.sh

version: 2
agent_loopback: false
log: ${NGROK_LOG_FILE}
log_level: info

tunnels:
  ${TUNNEL_NAME}:
    proto: http
    addr: ${BFF_WEBHOOK_PORT}
    host_header: localhost
    inspect: false
    bind_tls: true
    schemes:
      - https
    region: ${TUNNEL_REGION}
EOF

    success "Config written to ${NGROK_CONFIG_FILE}"
    info "Note: You must set your authtoken first:"
    info "  ngrok config add-authtoken <YOUR_TOKEN>"
    info "  Get your token at: https://dashboard.ngrok.com/get-started/your-authtoken"
}

start_tunnel() {
    info "Starting ngrok tunnel: ${TUNNEL_NAME} → http://127.0.0.1:${BFF_WEBHOOK_PORT}"

    # Check if already running
    if pgrep -f "ngrok.*${TUNNEL_NAME}" &>/dev/null; then
        warn "Tunnel already running. Stopping first..."
        pkill -f "ngrok.*${TUNNEL_NAME}" || true
        sleep 2
    fi

    # Start ngrok in background
    nohup ngrok start --config="${NGROK_CONFIG_FILE}" "${TUNNEL_NAME}" \
        >> "${NGROK_LOG_FILE}" 2>&1 &

    local pid=$!
    info "ngrok started (PID: ${pid})"

    # Wait for tunnel to establish
    info "Waiting for public URL (up to 15s)..."
    local public_url=""
    for i in $(seq 1 30); do
        sleep 0.5
        public_url=$(grep -o 'https://[^ ]*\.ngrok\.app' "${NGROK_LOG_FILE}" 2>/dev/null | tail -1 || true)
        if [[ -n "${public_url}" ]]; then
            break
        fi
    done

    if [[ -z "${public_url}" ]]; then
        error "Failed to get public URL after 15s"
        error "Check logs: ${NGROK_LOG_FILE}"
        exit 1
    fi

    # Verify tunnel is responding
    if curl -s --fail --max-time 5 "${public_url}/api/webhook/status" &>/dev/null; then
        success "Tunnel verified: ${public_url}"
    else
        warn "Tunnel URL is up but /api/webhook/status returned non-200"
        warn "This is OK if the BFF is still starting up"
    fi

    # Save URL to file
    cat > "${WEBHOOK_URL_FILE}" <<EOF
# Webhook URL Configuration
# Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Tool: ngrok ${TUNNEL_NAME} tunnel
# Local target: ${LOCAL_TARGET}
#
# Your public webhook base URL:
PUBLIC_WEBHOOK_BASE=${public_url}
#
# Full webhook endpoints:
# - Composio trigger:  ${public_url}/api/webhook/mail-event
# - MS Graph sub:      ${public_url}/api/webhook/outlook-subscription
# - Status check:      ${public_url}/api/webhook/status
# - Subscribe:         ${public_url}/api/webhook/subscribe
#
# ngrok dashboard: https://dashboard.ngrok.com
# ngrok logs: ${NGROK_LOG_FILE}
EOF

    success "Public URL saved to: ${WEBHOOK_URL_FILE}"
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  PUBLIC WEBHOOK BASE URL:${NC}"
    echo -e "  ${CYAN}${public_url}${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo "  Composio OUTLOOK_NEW_MESSAGE_TRIGGER webhook URL:"
    echo "  ${public_url}/api/webhook/mail-event"
    echo ""
    echo "  Microsoft Graph subscription notification URL:"
    echo "  ${public_url}/api/webhook/outlook-subscription"
    echo ""
    echo "  Next steps:"
    echo "  1. Register this URL in Composio dashboard"
    echo "  2. Or configure MS Graph mail subscription"
    echo "  3. Update Composio webhook URL in settings"
    echo ""
}

stop_tunnel() {
    info "Stopping ngrok tunnel..."
    pkill -f "ngrok.*${TUNNEL_NAME}" 2>/dev/null || true
    sleep 1
    if pgrep -f "ngrok.*${TUNNEL_NAME}" &>/dev/null; then
        pkill -9 -f "ngrok.*${TUNNEL_NAME}" 2>/dev/null || true
    fi
    success "Tunnel stopped"
    echo "" > "${WEBHOOK_URL_FILE}" 2>/dev/null || true
}

show_status() {
    echo ""
    echo "=== ngrok Tunnel Status ==="
    echo ""

    if ! check_ngrok_installed; then
        warn "ngrok is not installed"
        return
    fi

    if pgrep -f "ngrok.*${TUNNEL_NAME}" &>/dev/null; then
        success "Tunnel is running (PID: $(pgrep -f "ngrok.*${TUNNEL_NAME}" | head -1))"
    else
        warn "Tunnel is not running"
    fi

    if [[ -f "${WEBHOOK_URL_FILE}" ]]; then
        echo ""
        cat "${WEBHOOK_URL_FILE}"
    fi

    echo ""
    echo "Recent ngrok log (last 5 lines):"
    tail -5 "${NGROK_LOG_FILE}" 2>/dev/null || echo "  (no log file)"
    echo ""
}

setup_systemd_service() {
    info "Setting up systemd user service..."

    local service_dir="${HOME}/.config/systemd/user"
    mkdir -p "${service_dir}"

    cat > "${service_dir}/ngrok-webhook.service" <<EOF
[Unit]
Description=Ngrok Webhook Tunnel for Mail Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/ngrok start --config=${HOME}/.config/ngrok/ngrok.yml mail-webhook
Restart=on-failure
RestartSec=5
StandardOutput=append:${NGROK_LOG_FILE}
StandardError=append:${NGROK_LOG_FILE}
WorkingDirectory=${HOME}

[Install]
WantedBy=default.target
EOF

    # Reload systemd
    systemctl --user daemon-reload 2>/dev/null || true
    success "systemd service created: ~/.config/systemd/user/ngrok-webhook.service"
    info "To enable on boot: systemctl --user enable ngrok-webhook.service"
    info "To start now:         systemctl --user start ngrok-webhook.service"
}

# ─── Main ───────────────────────────────────────────────────────────────────

COMMAND="${1:-start}"

case "${COMMAND}" in
    --install)
        install_ngrok
        configure_ngrok
        ;;
    --status)
        show_status
        ;;
    --stop)
        stop_tunnel
        ;;
    --systemd)
        install_ngrok
        configure_ngrok
        setup_systemd_service
        ;;
    start|"")
        if ! check_ngrok_installed; then
            error "ngrok is not installed"
            info "Run: bash scripts/setup-ngrok-tunnel.sh --install"
            exit 1
        fi
        start_tunnel
        ;;
    *)
        echo "Usage: $0 {start|install|status|stop|systemd}"
        exit 1
        ;;
esac
