apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mery-ingress
  namespace: mery
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  tls:
    - hosts:
        - true-sight.asia
        - bff.true-sight.asia
      secretName: mery-tls
  rules:
    - host: true-sight.asia
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bff-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webui-svc
                port:
                  number: 80
    - host: bff.true-sight.asia
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bff-svc
                port:
                  number: 80
